data:
  name: cora_ml
  n_base: 2
  n_novel_list: [1, 1, 1, 1, 1]

model:
  in_feature: 2879
  hidden_feature: 512
  semantic_feature: 256
  output_dim: 128
  enc_layer: 2
  dec_layer: 2
  dis_layer: 2
